<table>
    <thead>
        <tr>
            <th scope="col">Titre</th>
            <th scope="col">Date de création</th>
            <th scope="col">Image</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($articles as $article): ?>
            <tr id="article-<?=htmlspecialchars($article['idArt']);?>">
                <td><?=htmlspecialchars($article['libArt']);?></td>
                <td><?=(new DateTimeImmutable($article['dtArt']))->format('d/m/Y');?></td>
                <td>
                    <?php if ($article['imgArt']): ?>
                        <img src="images/<?=htmlspecialchars($article['imgArt']);?>" alt="">
                    <?php endif; ?>
                </td>
                <td>
                    <a href="edit_article.php?id=<?=htmlspecialchars($article['idArt']);?>"><i class="fa-solid fa-pen-to-square"></i> Modifier</a>
                    <a class="delete-article-button" 
                       href="delete_article.php?id=<?=htmlspecialchars($article['idArt']);?>"
                       data-ajax="delete_article_ajax.php?id=<?=htmlspecialchars($article['idArt']);?>"><i class="fa-solid fa-trash-can"></i> Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </body>
</table>
    