<section>
    <h2>Les derniers articles</h2>
    <?php // foreach ($articles as $article){ ?>
    <?php foreach ($articles as $article): ?>
        <article>
            <h3><?=htmlspecialchars($article['libArt']);?></h3>
            <small>Créé le <?=(new DateTimeImmutable($article['dtArt']))->format('d/m/Y');?></small>
            
            <?php if ($article['imgArt']): ?>
                <img src="images/<?=htmlspecialchars($article['imgArt']);?>" alt="">
            <?php endif; ?>

            <p><?=htmlspecialchars($article['resArt'])?htmlspecialchars($article['resArt']):substr(htmlspecialchars($article['txtArt']),0,150) . ' [...]';?> </p>
            <a href="article.php?id=<?=$article['idArt'];?>">Lire la suite</a>
        </article>
    <?php // } ?>
    <?php endforeach; ?>
</section>
    